#
# embedXcode
# ----------------------------------
# Embedded Computing on Xcode
#
# Copyright © Rei VILO, 2010-2015
# http://embedxcode.weebly.com
# All rights reserved
#
# Last update: Nov 12, 2015 release 4.0.3
#

# ----------------------------------
# DO NOT EDIT THIS FILE.
# ----------------------------------

EMBEDXCODE_RELEASE      = 4.0.3
# ~
EMBEDXCODE_EDITION      = embedXcode for Wiring / Arduino
# ~~
EMBEDXCODE_DATE         = Nov 12, 2015
EMBEDXCODE_MESSAGE      = Stability improvement for Arduino 1.6.5 and Energia 17
# ~
EMBEDXCODE_TEMPLATE     = ePsiEJEtRXnDNaFGpywBX9vzeNQP4vUb
# ~~


# Arduino.ORG
# ----------------------------------
#
ARDUINO_ORG_RELEASE     = 1.7.7


# Arduino.CC or Genuino with Boards Manager
# ----------------------------------
#
ARDUINO_CC_RELEASE      = 1.6.6

ARDUINO_AVR_RELEASE     = 1.6.5
ARDUINO_SAM_RELEASE     = 1.6.5
ARDUINO_SAMD_RELEASE    = 1.6.2

# Boards for Arduino.CC 1.6.5 or Genuino
#
ADAFRUIT_AVR_RELEASE    = 1.4.0

COSA_AVR_RELEASE        = 1.1.0

DIGISPARK_AVR_RELEASE   = 1.6.5
DIGISPARK_SAM_RELEASE   = 1.6.5

ESP8266_RELEASE         = 1.6.5-947-g39819f0

INTEL_EDISON_RELEASE    = 1.6.2+1.0
INTEL_GALILEO_RELEASE   = 1.6.2+1.0

LINKIT_ONE_RELEASE      = 1.1.17

LITTLEROBOTFRIENDS_AVR_RELEASE = 1.6.0

PANSTAMP_AVR_RELEASE    = 1.5.2
PANSTAMP_MSP_RELEASE    = 1.0.5

REDBEARLAB_AVR_RELEASE  = 1.0.0
REDBEARLAB_NRF_RELEASE  = 1.0.0

RFDUINO_RELEASE         = 2.3.1
